# Generated by Django 5.2.4 on 2025-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
